version: 2

sources:
  - name: raw_data
    meta:
      external_location: "data/{name}.csv"
    tables:
      - name: assesments
      - name: courses
      - name: studentAssesment
      - name: studentInfo
      - name: studentRegistration
      - name: studentVle
      - name: vle